name = "AIT: Remixed"
author = "DrTheo_, AmbleLabs Moderation Team"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12ff17941bb966867d7b262b05829ca2b663c804828b443e8cfada61a509e68f"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
