name = "AIT: Remixed"
author = "DrTheo_, AmbleLabs Moderation Team"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac8f5bfd31d41bf9ce2cb72160e8100d40e3793d382e31ff124f0d42364a884e"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
