name = "AIT: Remixed"
author = "DrTheo_, AmbleLabs Moderation Team"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcab893a4b110ce82f8609c66786253495dc39eefabfec6d383d20cb975068f3"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
